name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - android-apk

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 20

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install dependencies
        run: npm install

            - name: Create web directory
        run: |
          mkdir -p www
          rsync -a ./ www/ \
            --exclude '.git/' \
            --exclude '.github/' \
            --exclude 'node_modules/' \
            --exclude 'android/' \
            --exclude 'www/' \
            --exclude 'package.json' \
            --exclude 'package-lock.json' \
            --exclude 'capacitor.config.json'

      - name: Add Android platform
        run: npx cap add android

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Gestionale-VG-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
